application: checknerds
version: arizona
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- appstats: on

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /files
  static_dir: files

- url: /css
  static_dir: css

- url: /(.*)\.css
  static_files: /css/(.*)\.css
  upload: /css/(.*)\.css

- url: /
  script: views/main.py

- url: /about
  script: views/miscellaneous.py

- url: /docs.+
  script: views/miscellaneous.py

- url: /Login.+
  script: views/auth.py

- url: /Logout.+
  script: views/auth.py

- url: /j/.*
  script: views/ajax.py

- url: /workers/done_item
  script: workers/done_item.py

- url: /workers/.+
  script: workers/stats_after_add.py

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: /

- url: /robots.txt
  static_files: files/robots.txt
  upload: /

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: /views/errorpages.py
