application: checknerds
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /files
  static_dir: files

- url: /css
  static_dir: css

- url: /(.*)\.css
  static_files: /css/(.*)\.css
  upload: /css/(.*)\.css

- url: /
  script: hello.py

- url: /about
  script: miscellaneous.py

- url: /blog
  script: miscellaneous.py

- url: /guestbook
  script: miscellaneous.py

- url: /statstics
  script: hello.py

- url: /Login.+
  script: hello.py

- url: /Logout.+
  script: hello.py

- url: /additem
  script: tarsusaItemCore.py

- url: /edititem/.*
  script: tarsusaItemCore.py

- url: /removeItem/.*
  script: tarsusaItemCore.py

- url: /AddFriend/.*
  script: friends.py

- url: /RemoveFriend/.*
  script: friends.py

- url: /i/.*
  script: hello.py

- url: /doneItem/.*
  script: tarsusaItemCore.py

- url: /undoneItem/.*
  script: tarsusaItemCore.py

- url: /tag
  script: tag.py

- url: /FindFriend
  script: friends.py

- url: /donelog
  script: hello.py

- url: /donelog/.*
  script: hello.py

- url: /user/.*
  script: hello.py

- url: /tag/.*
  script: tag.py

- url: /tag/
  script: tag.py

- url: /img
  script: hello.py

- url: /m/.+
  script: mobile.py

- url: /ajax/.+
  script: ajax.py

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: /

- url: /robots.txt
  static_files: files/robots.txt
  upload: /

- url: /.*
  static_files: pages/404.html
  upload: /.*
