application: checknerds
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /(.*)\.css
  static_files: /\1
  upload: /

- url: /
  script: hello.py

- url: /about
  script: miscellaneous.py

- url: /blog
  script: miscellaneous.py

- url: /guestbook
  script: miscellaneous.py

- url: /statstics
  script: hello.py

- url: /Login/.+
  script: hello.py

- url: /SignIn
  script: hello.py

- url: /SignOut/.+
  script: hello.py

- url: /Add
  script: hello.py

- url: /additem
  script: hello.py

- url: /edititem/.*
  script: hello.py

- url: /removeItem/.*
  script: hello.py

- url: /AddFriend/.*
  script: hello.py

- url: /RemoveFriend/.*
  script: hello.py

- url: /i/.*
  script: hello.py

- url: /doneItem/.*
  script: hello.py

- url: /undoneItem/.*
  script: hello.py

- url: /tag
  script: hello.py

- url: /FindFriend
  script: hello.py

- url: /donelog
  script: hello.py

- url: /donelog/.*
  script: hello.py

- url: /user/.*
  script: hello.py

- url: /tag/.*
  script: hello.py

- url: /tag/
  script: hello.py

- url: /img
  script: hello.py

- url: /dashboard
  script: hello.py

- url: /m/.+
  script: mobile.py

- url: /ajax/.+
  script: ajax.py

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: /

- url: /robots.txt
  static_files: robots.txt
  upload: /

- url: /.*
  static_files: pages/404.html
  upload: /.*
