application: checknerds
version: arizona
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- appstats: on

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /files
  static_dir: files

- url: /css
  static_dir: css

- url: /(.*)\.css
  static_files: /css/(.*)\.css
  upload: /css/(.*)\.css

- url: /
  script: views/main.py

- url: /about
  script: views/miscellaneous.py

- url: /blog
  script: views/miscellaneous.py

- url: /guestbook
  script: views/miscellaneous.py

- url: /docs.+
  script: views/miscellaneous.py

- url: /labs.+
  script: views/miscellaneous.py

- url: /Login.+
  script: views/auth.py

- url: /Logout.+
  script: views/auth.py

- url: /additem
  script: tarsusaItemCore.py

- url: /edititem/.*
  script: tarsusaItemCore.py

- url: /removeItem/.*
  script: tarsusaItemCore.py

- url: /duetoday/.*
  script: tarsusaItemCore.py

- url: /i/.*
  script: mobile.py

- url: /item/.*
  script: views/item.py

- url: /doneItem/.*
  script: tarsusaItemCore.py

- url: /undoneItem/.*
  script: tarsusaItemCore.py

- url: /tag
  script: tag.py

- url: /donelog.*
  script: userpage.py

- url: /user/.*
  script: userpage.py

- url: /tag/.*
  script: tag.py

- url: /tag/
  script: tag.py

- url: /image.*
  script: views/image.py

- url: /flushcache
  script: views/miscellaneous.py

- url: /cron_flushcache
  script: views/miscellaneous.py

- url: /backend/.+
  script: backend.py

- url: /service/.+
  script: service.py

- url: /m.*
  script: mobile.py

- url: /ajax/.+
  script: ajax.py

- url: /patch/.+
  script: patcher.py

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: /

- url: /cronmail
  script: cronmail.py

- url: /robots.txt
  static_files: files/robots.txt
  upload: /

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: /views/errorpages.py
