application: checknerds
version: arizona
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- appstats: on

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /files
  static_dir: files

- url: /css
  static_dir: css

- url: /(.*)\.css
  static_files: /css/(.*)\.css
  upload: /css/(.*)\.css

- url: /
  script: views/main.py

- url: /about
  script: views/miscellaneous.py

- url: /blog
  script: views/miscellaneous.py

- url: /guestbook
  script: views/miscellaneous.py

- url: /docs.+
  script: views/miscellaneous.py

- url: /labs.+
  script: views/miscellaneous.py

- url: /Login.+
  script: views/auth.py

- url: /Logout.+
  script: views/auth.py

- url: /additem
  script: views/ajax.py

- url: /duetoday/.*
  script: views/ajax.py

- url: /duetomorrow/.*
  script: views/ajax.py

- url: /j/.*
  script: views/ajax.py

- url: /tag
  script: tag.py

- url: /donelog.*
  script: userpage.py

- url: /user/.*
  script: userpage.py

- url: /tag/.*
  script: tag.py

- url: /tag/
  script: tag.py

- url: /flushcache
  script: views/miscellaneous.py

- url: /cron_flushcache
  script: views/miscellaneous.py

- url: /backend/.+
  script: backend.py

- url: /workers/done_item
  script: workers/done_item.py

- url: /workers/.+
  script: workers/stats_after_add.py

- url: /service/.+
  script: service.py

- url: /ajax/.+
  script: views/ajax.py

- url: /patch/.+
  script: patcher.py

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: /

- url: /cronmail
  script: cronmail.py

- url: /robots.txt
  static_files: files/robots.txt
  upload: /

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: /views/errorpages.py
