application: nevada
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /pages
  static_dir: pages

- url: /(.*)\.css
  static_files: /\1
  upload: /

- url: /
  script: hello.py

- url: /About
  script: hello.py

- url: /Blog
  script: hello.py

- url: /Statstics
  script: hello.py

- url: /Login
  script: hello.py

- url: /SignIn
  script: hello.py

- url: /SignOut
  script: hello.py

- url: /Add
  script: hello.py

- url: /additem
  script: hello.py

- url: /AddFriend/.*
  script: hello.py

- url: /i/.*
  script: hello.py

- url: /doneItem/.*
  script: hello.py

- url: /undoneItem/.*
  script: hello.py

- url: /tag
  script: hello.py

- url: /FindFriend
  script: hello.py

- url: /donelog
  script: hello.py

- url: /user/.*
  script: hello.py

- url: /tag/.*
  script: hello.py

- url: /.*
  static_files: pages/404.html
  upload: pages/.*
